version: "3.9"
services:
  catobreed_client:
    container_name: catobreed_client
    image: node:16-alpine
    working_dir: "/app"
    command: sh -c "yarn && yarn start"
    volumes:
      - ./:/app
      - ~/.gitconfig:/root/.gitconfig
      - client_node_modules:/app/node_modules
    ports:
      - 3000:3000
    environment:
      CHOKIDAR_USEPOLLING: "true"
volumes:
  client_node_modules:
